[project]
name = "py-web-scraping-03"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "django>=5.1.7",
    "geckodriver>=0.0.1",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "selenium>=4.29.0",
    "webdriver-manager>=4.0.2",
]
