# Generated by Django 5.1.7 on 2025-03-19 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GDPCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'GDP Categories',
            },
        ),
        migrations.CreateModel(
            name='GDPData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(max_length=255)),
                ('geo_area', models.CharField(max_length=100)),
                ('time_period', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('unit', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='eurostat_manager.gdpcategory')),
            ],
            options={
                'verbose_name_plural': 'GDP Data',
                'indexes': [models.Index(fields=['category', 'indicator', 'geo_area', 'time_period'], name='eurostat_ma_categor_26c6a9_idx')],
            },
        ),
    ]
