# Generated by Django 5.1.7 on 2025-03-20 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eurostat_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GDPTableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(max_length=255)),
                ('unit', models.CharField(default='Million euro', max_length=50)),
                ('geo_area', models.CharField(default='European Union', max_length=100)),
                ('year_2019', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('year_2020', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('year_2021', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('year_2022', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('year_2023', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('year_2024', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GDP Table Row',
                'verbose_name_plural': 'GDP Table Data',
            },
        ),
    ]
