# Generated by Django 5.1.7 on 2025-03-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eurostat_manager', '0002_gdptabledata'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdptabledata',
            name='year_2015',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='gdptabledata',
            name='year_2016',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='gdptabledata',
            name='year_2017',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='gdptabledata',
            name='year_2018',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='gdptabledata',
            name='geo_area',
            field=models.CharField(max_length=100),
        ),
    ]
