# Generated by Django 5.1.7 on 2025-03-20 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eurostat_manager', '0003_gdptabledata_year_2015_gdptabledata_year_2016_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gdpdata',
            name='category',
        ),
        migrations.DeleteModel(
            name='GDPTableData',
        ),
        migrations.DeleteModel(
            name='GDPCategory',
        ),
        migrations.DeleteModel(
            name='GDPData',
        ),
    ]
