# Generated by Django 5.1.7 on 2025-03-20 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GDPCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'GDP Categories',
            },
        ),
        migrations.CreateModel(
            name='GDPTableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(max_length=255)),
                ('unit', models.CharField(default='Million euro', max_length=50)),
                ('geo_area', models.CharField(max_length=100)),
                ('year_2015', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('year_2016', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('year_2017', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('year_2018', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('year_2019', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('year_2020', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('year_2021', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('year_2022', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('year_2023', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('year_2024', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GDP Table Row',
                'verbose_name_plural': 'GDP Table Data',
            },
        ),
        migrations.CreateModel(
            name='GDPData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(max_length=255)),
                ('geo_area', models.CharField(max_length=100)),
                ('time_period', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('unit', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='scraper.gdpcategory')),
            ],
            options={
                'verbose_name_plural': 'GDP Data',
                'indexes': [models.Index(fields=['category', 'indicator', 'geo_area', 'time_period'], name='scraper_gdp_categor_156dd1_idx')],
            },
        ),
    ]
