# Generated by Django 5.1.7 on 2025-03-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_remove_gdptabledata_year_2015_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdptabledata',
            name='geo_area',
            field=models.CharField(max_length=500),
        ),
    ]
