# Generated by Django 5.1.7 on 2025-03-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_alter_gdptabledata_geo_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gdpdata',
            name='category',
        ),
        migrations.AlterField(
            model_name='gdptabledata',
            name='year_2019',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gdptabledata',
            name='year_2020',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gdptabledata',
            name='year_2021',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gdptabledata',
            name='year_2022',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gdptabledata',
            name='year_2023',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gdptabledata',
            name='year_2024',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='GDPCategory',
        ),
        migrations.DeleteModel(
            name='GDPData',
        ),
    ]
