# Generated by Django 5.1.7 on 2025-03-24 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_remove_gdpdata_category_alter_gdptabledata_year_2019_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GDPData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('value', models.CharField(blank=True, max_length=50, null=True)),
                ('flag', models.CharField(blank=True, choices=[('b', 'Break in time series'), ('p', 'Provisional'), ('e', 'Estimated'), (None, 'No flag')], max_length=1, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GDP Data Record',
                'verbose_name_plural': 'GDP Data Records',
                'ordering': ['geo_area__code', 'year'],
            },
        ),
        migrations.CreateModel(
            name='GeoArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_kosovo', models.BooleanField(default=False)),
                ('is_eu', models.BooleanField(default=False)),
                ('is_euro_area', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Geographic Area',
                'verbose_name_plural': 'Geographic Areas',
                'ordering': ['code'],
            },
        ),
        migrations.DeleteModel(
            name='GDPTableData',
        ),
        migrations.AddField(
            model_name='gdpdata',
            name='geo_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gdp_records', to='scraper.geoarea'),
        ),
        migrations.AlterUniqueTogether(
            name='gdpdata',
            unique_together={('geo_area', 'year')},
        ),
    ]
